<a href="https://colab.research.google.com/github/DangGiaChi/Tensorflow-Course/blob/main/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

**Basic Tensors**

In [2]:
tensor_zero_d = tf.constant(12)

In [3]:
print(tensor_zero_d)

tf.Tensor(12, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([12, 5, 18, 11.], dtype = tf.float16)

In [5]:
print(tensor_one_d)

tf.Tensor([12.  5. 18. 11.], shape=(4,), dtype=float16)


In [6]:
print(tensor_one_d.shape)

(4,)


In [7]:
print(tensor_one_d.ndim)

1


In [8]:
tensor_one_d_2 = tf.constant([5, 9, 12.], dtype = tf.float32)
tensor_one_d_2_int = tf.cast(tensor_one_d_2, dtype = tf.int16)
print(tensor_one_d_2)
print(tensor_one_d_2_int)

tf.Tensor([ 5.  9. 12.], shape=(3,), dtype=float32)
tf.Tensor([ 5  9 12], shape=(3,), dtype=int16)


In [9]:
tensor_string = tf.constant(["Hello", "Hi"])
print(tensor_string)

tf.Tensor([b'Hello' b'Hi'], shape=(2,), dtype=string)


In [10]:
np_array = np.array([12, 5, 18, 11])
print(np_array)

[12  5 18 11]


In [11]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([12  5 18 11], shape=(4,), dtype=int64)


In [12]:
eye_tensor_1 = tf.eye(3, 2)
print(eye_tensor_1)

eye_tensor_2 = tf.eye(3, dtype = tf.bool, batch_shape = [3, 2])
print(eye_tensor_2)

tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]


 [[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]


 [[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]], shape=(3, 2, 3, 3), dtype=bool)


In [13]:
fill_tensor = tf.fill([5, 4], 12.05)
print(fill_tensor)

tf.Tensor(
[[12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]], shape=(5, 4), dtype=float32)


In [14]:
ones_tensor = tf.ones([5, 4])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(5, 4), dtype=float32)


In [15]:
sample_tensor = tf.constant([[2, 3, 5],[5, 8,9]])
ones_like_tensor = tf.ones_like(sample_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [16]:
zeros_tensor = tf.zeros([2, 3])
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [17]:
print(tf.shape(sample_tensor))

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [18]:
rank_tensor_1 = tf.constant(12.05)
rank_tensor_2 = tf.constant([12.05])
rank_tensor_3 = sample_tensor

print(tf.rank(rank_tensor_1))
print(tf.rank(rank_tensor_2))
print(tf.rank(rank_tensor_3))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [19]:
print(tf.size(sample_tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [20]:
print(tf.size(sample_tensor, out_type = tf.float16))

tf.Tensor(6.0, shape=(), dtype=float16)


In [21]:
random_normal_tensor = tf.random.normal([3, 2], mean = 100, stddev = 1.5)
print(random_normal_tensor)

tf.Tensor(
[[97.760796 99.87523 ]
 [98.84369  99.30642 ]
 [99.07979  99.310715]], shape=(3, 2), dtype=float32)


In [22]:
random_uniform_tensor = tf.random.uniform([2, 3], 3, 10, tf.int32)
print(random_uniform_tensor)

tf.Tensor(
[[6 4 8]
 [6 3 9]], shape=(2, 3), dtype=int32)


**Indexing**

In [23]:
indexed_tensor = tf.constant([5, 6, 3, 8, 9, 12])
print(indexed_tensor[:4])
print(indexed_tensor[1:4])
print(indexed_tensor[:5:2])
print(indexed_tensor[:-1])

tf.Tensor([5 6 3 8], shape=(4,), dtype=int32)
tf.Tensor([6 3 8], shape=(3,), dtype=int32)
tf.Tensor([5 3 9], shape=(3,), dtype=int32)
tf.Tensor([5 6 3 8 9], shape=(5,), dtype=int32)


**Maths Operations**

In [24]:
sample_x = tf.constant([-6, 12])
print(tf.abs(sample_x))

tf.Tensor([ 6 12], shape=(2,), dtype=int32)


In [25]:
complex_tensor = tf.constant(3 + 4j)
print(tf.abs(complex_tensor))

tf.Tensor(5.0, shape=(), dtype=float64)


In [26]:
print(tf.sqrt(tf.constant(5**2, dtype = tf.float16)))

tf.Tensor(5.0, shape=(), dtype=float16)


In [27]:
x_1 = tf.ones([3, 2])
x_2 = tf.fill([3, 2], 5.)
print(x_1 + x_2)
print(tf.add(x_1, x_2))

tf.Tensor(
[[6. 6.]
 [6. 6.]
 [6. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[6. 6.]
 [6. 6.]
 [6. 6.]], shape=(3, 2), dtype=float32)


In [28]:
x_3 = tf.zeros([3, 2])
print(tf.divide(x_1, x_3))
print(tf.math.divide_no_nan(x_1, x_3))

tf.Tensor(
[[inf inf]
 [inf inf]
 [inf inf]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [29]:
argmax_tensor_1 = tf.constant([100, 250, 15, 20])
argmax_tensor_2 = tf.constant([[2, 20, 30, 3, 6],
                            [3, 11, 16, 1, 8],
                            [14, 45, 23, 5, 27]]
                            )
print(tf.math.argmax(argmax_tensor_1))
print(tf.math.argmax(argmax_tensor_2))
print(tf.math.argmax(argmax_tensor_2, 0))
print(tf.math.argmin(argmax_tensor_2, 0))
print(tf.math.argmax(argmax_tensor_2, 1))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [30]:
a = tf.constant([2, 4])
b = tf.constant([2])
print(tf.equal(a, b))

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [31]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
print(pow(x, y))

tf.Tensor(
[[  256 65536]
 [    9    27]], shape=(2, 2), dtype=int32)


In [32]:
x = tf.constant([[1, -1, 1], [1, 1, 5]], dtype = tf.float16)
print(tf.math.reduce_sum(x))
print(tf.reduce_sum(x, 0, keepdims = True))
print(tf.math.reduce_sum(x, 1))

tf.Tensor(8.0, shape=(), dtype=float16)
tf.Tensor([[2. 0. 6.]], shape=(1, 3), dtype=float16)
tf.Tensor([1. 7.], shape=(2,), dtype=float16)


In [33]:
print(tf.reduce_max(x))
print(tf.reduce_min(x))
print(tf.reduce_mean(x))

tf.Tensor(5.0, shape=(), dtype=float16)
tf.Tensor(-1.0, shape=(), dtype=float16)
tf.Tensor(1.333, shape=(), dtype=float16)


In [34]:
x = tf.constant([[18, 11, 100, 20], [5, 12, 9, 15]])
print(tf.math.top_k(x, 2))

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  20],
       [ 15,  12]], dtype=int32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 1]], dtype=int32)>)


**Linear Algebra Operations**

In [35]:
x_1 = tf.constant([[12, 5, 20],
                   [18, 11, 25]])
x_2 = tf.constant([[5, 9, 15, 20],
                   [4, 3, 16, 24],
                   [3, 7, 10, 6]])
print(tf.linalg.matmul(x_1, x_2))
print(x_1 @ x_2)

tf.Tensor(
[[140 263 460 480]
 [209 370 696 774]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[140 263 460 480]
 [209 370 696 774]], shape=(2, 4), dtype=int32)


In [36]:
print(tf.transpose(x_2))

tf.Tensor(
[[ 5  4  3]
 [ 9  3  7]
 [15 16 10]
 [20 24  6]], shape=(4, 3), dtype=int32)


In [37]:
x_1 = tf.constant([[12, 5, 20],
                   [18, 11, 25]])
x_3 = tf.constant([[5, 9, 15],
                   [4, 3, 16],
                   [5, 9, 16],
                   [15, 6, 10]])
print(tf.linalg.matmul(x_1, x_3, transpose_b = True))

tf.Tensor(
[[405 383 425 410]
 [564 505 589 586]], shape=(2, 4), dtype=int32)


In [38]:
x_4 = tf.constant([[4, 5, 6]])
x_5 = tf.constant([[9], [10], [1]])
print(x_4@x_5)

tf.Tensor([[92]], shape=(1, 1), dtype=int32)


In [39]:
a = tf.random.uniform((3, 2, 3), dtype = tf.int32, minval = 1, maxval = 10)
b = tf.random.uniform((3, 3, 5), dtype = tf.int32, minval = 1, maxval = 10)
print(a)
print(b)
print(a@b)

tf.Tensor(
[[[1 6 4]
  [7 8 8]]

 [[2 6 8]
  [6 3 3]]

 [[1 8 1]
  [5 9 5]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[9 2 1 2 2]
  [8 3 1 3 4]
  [9 5 2 6 2]]

 [[5 6 5 3 9]
  [1 2 7 6 4]
  [5 9 2 3 1]]

 [[6 3 7 6 1]
  [3 7 7 7 5]
  [7 8 3 4 3]]], shape=(3, 3, 5), dtype=int32)
tf.Tensor(
[[[ 93  40  15  44  34]
  [199  78  31  86  62]]

 [[ 56  96  68  66  50]
  [ 48  69  57  45  69]]

 [[ 37  67  66  66  44]
  [ 92 118 113 113  65]]], shape=(3, 2, 5), dtype=int32)


In [40]:
test_a = tf.constant([[5, 8, 5], [8, 2, 1]])
test_b = tf.constant([[1, 7, 4, 1, 9],
  [2, 6, 3, 6, 7,],
  [5, 7, 4, 5, 7,]])
print(test_a@test_b)

tf.Tensor(
[[ 46 118  64  78 136]
 [ 17  75  42  25  93]], shape=(2, 5), dtype=int32)


In [41]:
band_tensor = tf.constant([
    [ 0,  5,  2, 3],
    [-1,  0,  1, 2],
    [-2, -1,  0, 1],
    [-3, -2, -1, 0]
                           ])
print(tf.linalg.band_part(band_tensor, 2, -1))
print(tf.linalg.band_part(band_tensor, 1, 1))

tf.Tensor(
[[ 0  5  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  5  0  0]
 [-1  0  1  0]
 [ 0 -1  0  1]
 [ 0  0 -1  0]], shape=(4, 4), dtype=int32)


**Explanation of tf.linalg.band_part(input, num_lower, num_upper)**  
*m: the index of the row*  
*n: the index of the column*  
Considering a 4x4 matrix, then:
```  
tensor_m_n = [  
[0, -1, -2, -3],  
[1, 0, -1, -2],  
[2, 1, 0, -1],  
[3, 2, 1, 0]]  
tensor_n_m = [  
[0, 1, 2, 3],  
[-1, 0, 1, 2],  
[-2, -1, 0, 1],  
[-3, -2, -1, 0]]
```
Considering an element [m, n], then:  
`in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower) && (num_upper < 0 || (n-m) <= num_upper)`  
In short:
- `num_lower` indicates the number of subdiagonals to keep. If negative, keep entire lower triangle.
- `num_upper` indicates the number of superdiagonals to keep. If negative, keep entire upper triangle.  

Explanation:
- If `num_lower < 0` or `num_upper < 0`, this is an easy case.
- Looking at a point in the lower half of the diagonal, then its `m-n` will be positive, and will be compared to `num_lower`, which is easy to understand. Its `n-m` will then be negative, and `n-m <= num_upper` will always be true (since `num_upper > 0`)
- Similar to a point in the upper half of the diagonal.

**Einsum**

In [44]:
A = tf.random.uniform([4,5], 0, 20, dtype = tf.int32)
B = tf.random.uniform([5,2], 5, 25, dtype = tf.int32)
print("Matmul: C = ", tf.matmul(A, B))
print("Einsum: C = ", "\n", np.einsum("ij, jk -> ik", A, B))

Matmul: C =  tf.Tensor(
[[756 715]
 [687 560]
 [567 495]
 [683 699]], shape=(4, 2), dtype=int32)
Einsum: C =  
 [[756 715]
 [687 560]
 [567 495]
 [683 699]]


In [46]:
A = tf.random.uniform([4, 5], 0, 20, dtype = tf.int32)
B = tf.random.uniform([4, 5], 5, 25, dtype = tf.int32)
print("Element-wise multiplication: C = ", A*B)
print("Einsum: C = \n", np.einsum("ij, ij -> ij", A, B))

Element-wise multiplication: C =  tf.Tensor(
[[ 84 264 195 299 216]
 [ 55  54 234 322 336]
 [221 132 128 432  60]
 [117  60 266  39  45]], shape=(4, 5), dtype=int32)
Einsum: C = 
 [[ 84 264 195 299 216]
 [ 55  54 234 322 336]
 [221 132 128 432  60]
 [117  60 266  39  45]]


If we're only dealing with one matrix (say, when we're calculatating the transpose of matrix A), then -> is not needed.

In [48]:
A = tf.random.uniform([4, 5], 0, 20, dtype = tf.int32)
print("Transpose: AT = ", tf.transpose(A))
print("Einsum: AT = \n", np.einsum("ji", A))

Transpose: AT =  tf.Tensor(
[[16 11  9 14]
 [ 4 14 18  6]
 [ 5 13 11  9]
 [ 7  5  0 16]
 [ 6  3  5  6]], shape=(5, 4), dtype=int32)
Einsum: AT = 
 [[16 11  9 14]
 [ 4 14 18  6]
 [ 5 13 11  9]
 [ 7  5  0 16]
 [ 6  3  5  6]]
