In [132]:
import tensorflow as tf
import numpy as np

**Basic Tensors**

In [133]:
tensor_zero_d = tf.constant(12)

In [134]:
print(tensor_zero_d)

tf.Tensor(12, shape=(), dtype=int32)


In [135]:
tensor_one_d = tf.constant([12, 5, 18, 11.], dtype = tf.float16)

In [136]:
print(tensor_one_d)

tf.Tensor([12.  5. 18. 11.], shape=(4,), dtype=float16)


In [137]:
print(tensor_one_d.shape)

(4,)


In [138]:
print(tensor_one_d.ndim)

1


In [139]:
tensor_one_d_2 = tf.constant([5, 9, 12.], dtype = tf.float32)
tensor_one_d_2_int = tf.cast(tensor_one_d_2, dtype = tf.int16)
print(tensor_one_d_2)
print(tensor_one_d_2_int)

tf.Tensor([ 5.  9. 12.], shape=(3,), dtype=float32)
tf.Tensor([ 5  9 12], shape=(3,), dtype=int16)


In [140]:
tensor_string = tf.constant(["Hello", "Hi"])
print(tensor_string)

tf.Tensor([b'Hello' b'Hi'], shape=(2,), dtype=string)


In [141]:
np_array = np.array([12, 5, 18, 11])
print(np_array)

[12  5 18 11]


In [142]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([12  5 18 11], shape=(4,), dtype=int64)


In [143]:
eye_tensor_1 = tf.eye(3, 2)
print(eye_tensor_1)

eye_tensor_2 = tf.eye(3, dtype = tf.bool, batch_shape = [3, 2])
print(eye_tensor_2)

tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]


 [[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]


 [[[ True False False]
   [False  True False]
   [False False  True]]

  [[ True False False]
   [False  True False]
   [False False  True]]]], shape=(3, 2, 3, 3), dtype=bool)


In [144]:
fill_tensor = tf.fill([5, 4], 12.05)
print(fill_tensor)

tf.Tensor(
[[12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]
 [12.05 12.05 12.05 12.05]], shape=(5, 4), dtype=float32)


In [145]:
ones_tensor = tf.ones([5, 4])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(5, 4), dtype=float32)


In [146]:
sample_tensor = tf.constant([[2, 3, 5],[5, 8,9]])
ones_like_tensor = tf.ones_like(sample_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [147]:
zeros_tensor = tf.zeros([2, 3])
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [148]:
print(tf.shape(sample_tensor))

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [149]:
rank_tensor_1 = tf.constant(12.05)
rank_tensor_2 = tf.constant([12.05])
rank_tensor_3 = sample_tensor

print(tf.rank(rank_tensor_1))
print(tf.rank(rank_tensor_2))
print(tf.rank(rank_tensor_3))

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [150]:
print(tf.size(sample_tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [151]:
print(tf.size(sample_tensor, out_type = tf.float16))

tf.Tensor(6.0, shape=(), dtype=float16)


In [152]:
random_normal_tensor = tf.random.normal([3, 2], mean = 100, stddev = 1.5)
print(random_normal_tensor)

tf.Tensor(
[[100.9079   97.42326]
 [ 97.38773 100.41212]
 [ 98.66231 100.3288 ]], shape=(3, 2), dtype=float32)


In [153]:
random_uniform_tensor = tf.random.uniform([2, 3], 3, 10, tf.int32)
print(random_uniform_tensor)

tf.Tensor(
[[4 7 5]
 [5 3 6]], shape=(2, 3), dtype=int32)


**Indexing**

In [154]:
indexed_tensor = tf.constant([5, 6, 3, 8, 9, 12])
print(indexed_tensor[:4])
print(indexed_tensor[1:4])
print(indexed_tensor[:5:2])
print(indexed_tensor[:-1])

tf.Tensor([5 6 3 8], shape=(4,), dtype=int32)
tf.Tensor([6 3 8], shape=(3,), dtype=int32)
tf.Tensor([5 3 9], shape=(3,), dtype=int32)
tf.Tensor([5 6 3 8 9], shape=(5,), dtype=int32)


**Maths Operations**

In [155]:
sample_x = tf.constant([-6, 12])
print(tf.abs(sample_x))

tf.Tensor([ 6 12], shape=(2,), dtype=int32)


In [156]:
complex_tensor = tf.constant(3 + 4j)
print(tf.abs(complex_tensor))

tf.Tensor(5.0, shape=(), dtype=float64)


In [157]:
print(tf.sqrt(tf.constant(5**2, dtype = tf.float16)))

tf.Tensor(5.0, shape=(), dtype=float16)


In [158]:
x_1 = tf.ones([3, 2])
x_2 = tf.fill([3, 2], 5.)
print(x_1 + x_2)
print(tf.add(x_1, x_2))

tf.Tensor(
[[6. 6.]
 [6. 6.]
 [6. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[6. 6.]
 [6. 6.]
 [6. 6.]], shape=(3, 2), dtype=float32)


In [159]:
x_3 = tf.zeros([3, 2])
print(tf.divide(x_1, x_3))
print(tf.math.divide_no_nan(x_1, x_3))

tf.Tensor(
[[inf inf]
 [inf inf]
 [inf inf]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [160]:
argmax_tensor_1 = tf.constant([100, 250, 15, 20])
argmax_tensor_2 = tf.constant([[2, 20, 30, 3, 6],
                            [3, 11, 16, 1, 8],
                            [14, 45, 23, 5, 27]]
                            )
print(tf.math.argmax(argmax_tensor_1))
print(tf.math.argmax(argmax_tensor_2))
print(tf.math.argmax(argmax_tensor_2, 0))
print(tf.math.argmin(argmax_tensor_2, 0))
print(tf.math.argmax(argmax_tensor_2, 1))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [161]:
a = tf.constant([2, 4])
b = tf.constant([2])
print(tf.equal(a, b))

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [162]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
print(pow(x, y))

tf.Tensor(
[[  256 65536]
 [    9    27]], shape=(2, 2), dtype=int32)


In [163]:
x = tf.constant([[1, -1, 1], [1, 1, 5]], dtype = tf.float16)
print(tf.math.reduce_sum(x))
print(tf.reduce_sum(x, 0, keepdims = True))
print(tf.math.reduce_sum(x, 1))

tf.Tensor(8.0, shape=(), dtype=float16)
tf.Tensor([[2. 0. 6.]], shape=(1, 3), dtype=float16)
tf.Tensor([1. 7.], shape=(2,), dtype=float16)


In [164]:
print(tf.reduce_max(x))
print(tf.reduce_min(x))
print(tf.reduce_mean(x))

tf.Tensor(5.0, shape=(), dtype=float16)
tf.Tensor(-1.0, shape=(), dtype=float16)
tf.Tensor(1.333, shape=(), dtype=float16)


In [165]:
x = tf.constant([[18, 11, 100, 20], [5, 12, 9, 15]])
print(tf.math.top_k(x, 2))

TopKV2(values=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  20],
       [ 15,  12]], dtype=int32)>, indices=<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 1]], dtype=int32)>)


**Linear Algebra Operations**

In [166]:
x_1 = tf.constant([[12, 5, 20],
                   [18, 11, 25]])
x_2 = tf.constant([[5, 9, 15, 20],
                   [4, 3, 16, 24],
                   [3, 7, 10, 6]])
print(tf.linalg.matmul(x_1, x_2))
print(x_1 @ x_2)

tf.Tensor(
[[140 263 460 480]
 [209 370 696 774]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[140 263 460 480]
 [209 370 696 774]], shape=(2, 4), dtype=int32)


In [167]:
print(tf.transpose(x_2))

tf.Tensor(
[[ 5  4  3]
 [ 9  3  7]
 [15 16 10]
 [20 24  6]], shape=(4, 3), dtype=int32)


In [168]:
x_1 = tf.constant([[12, 5, 20],
                   [18, 11, 25]])
x_3 = tf.constant([[5, 9, 15],
                   [4, 3, 16],
                   [5, 9, 16],
                   [15, 6, 10]])
print(tf.linalg.matmul(x_1, x_3, transpose_b = True))

tf.Tensor(
[[405 383 425 410]
 [564 505 589 586]], shape=(2, 4), dtype=int32)


In [169]:
x_4 = tf.constant([[4, 5, 6]])
x_5 = tf.constant([[9], [10], [1]])
print(x_4@x_5)

tf.Tensor([[92]], shape=(1, 1), dtype=int32)


In [170]:
a = tf.random.uniform((3, 2, 3), dtype = tf.int32, minval = 1, maxval = 10)
b = tf.random.uniform((3, 3, 5), dtype = tf.int32, minval = 1, maxval = 10)
print(a)
print(b)
print(a@b)

tf.Tensor(
[[[8 2 5]
  [6 9 2]]

 [[9 2 5]
  [6 3 2]]

 [[9 4 8]
  [6 6 1]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[9 3 4 8 6]
  [7 8 7 3 9]
  [5 4 7 5 8]]

 [[9 9 7 5 7]
  [3 1 3 5 6]
  [8 8 5 3 3]]

 [[7 1 5 1 2]
  [6 4 4 2 4]
  [9 3 5 3 7]]], shape=(3, 3, 5), dtype=int32)
tf.Tensor(
[[[111  60  81  95 106]
  [127  98 101  85 133]]

 [[127 123  94  70  90]
  [ 79  73  61  51  66]]

 [[159  49 101  41  90]
  [ 87  33  59  21  43]]], shape=(3, 2, 5), dtype=int32)


In [171]:
test_a = tf.constant([[5, 8, 5], [8, 2, 1]])
test_b = tf.constant([[1, 7, 4, 1, 9],
  [2, 6, 3, 6, 7,],
  [5, 7, 4, 5, 7,]])
print(test_a@test_b)

tf.Tensor(
[[ 46 118  64  78 136]
 [ 17  75  42  25  93]], shape=(2, 5), dtype=int32)


In [172]:
band_tensor = tf.constant([
    [ 0,  5,  2, 3],
    [-1,  0,  1, 2],
    [-2, -1,  0, 1],
    [-3, -2, -1, 0]
                           ])
print(tf.linalg.band_part(band_tensor, 2, -1))
print(tf.linalg.band_part(band_tensor, 1, 1))

tf.Tensor(
[[ 0  5  2  3]
 [-1  0  1  2]
 [-2 -1  0  1]
 [ 0 -2 -1  0]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0  5  0  0]
 [-1  0  1  0]
 [ 0 -1  0  1]
 [ 0  0 -1  0]], shape=(4, 4), dtype=int32)


**Explanation of tf.linalg.band_part(input, num_lower, num_upper)**  
*m: the index of the row*  
*n: the index of the column*  
Considering a 4x4 matrix, then:
```  
tensor_m_n = [  
[0, -1, -2, -3],  
[1, 0, -1, -2],  
[2, 1, 0, -1],  
[3, 2, 1, 0]]  
tensor_n_m = [  
[0, 1, 2, 3],  
[-1, 0, 1, 2],  
[-2, -1, 0, 1],  
[-3, -2, -1, 0]]
```
Considering an element [m, n], then:  
`in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower) && (num_upper < 0 || (n-m) <= num_upper)`  
In short:
- `num_lower` indicates the number of subdiagonals to keep. If negative, keep entire lower triangle.
- `num_upper` indicates the number of superdiagonals to keep. If negative, keep entire upper triangle.  

Explanation:
- If `num_lower < 0` or `num_upper < 0`, this is an easy case.
- Looking at a point in the lower half of the diagonal, then its `m-n` will be positive, and will be compared to `num_lower`, which is easy to understand. Its `n-m` will then be negative, and `n-m <= num_upper` will always be true (since `num_upper > 0`)
- Similar to a point in the upper half of the diagonal.

**Einsum**

In [173]:
A = tf.random.uniform([4,5], 0, 20, dtype = tf.int32)
B = tf.random.uniform([5,2], 5, 25, dtype = tf.int32)
print("Matmul: C = ", tf.matmul(A, B))
print("Einsum: C = ", "\n", np.einsum("ij, jk -> ik", A, B))

Matmul: C =  tf.Tensor(
[[637 638]
 [679 815]
 [569 544]
 [724 881]], shape=(4, 2), dtype=int32)
Einsum: C =  
 [[637 638]
 [679 815]
 [569 544]
 [724 881]]


In [174]:
A = tf.random.uniform([4, 5], 0, 20, dtype = tf.int32)
B = tf.random.uniform([4, 5], 5, 25, dtype = tf.int32)
print("Element-wise multiplication: C = ", A*B)
print("Einsum: C = \n", np.einsum("ij, ij -> ij", A, B))

Element-wise multiplication: C =  tf.Tensor(
[[208  80 140  28   8]
 [216 176 126   0 154]
 [288  12  56 414 414]
 [272  85  56   0 165]], shape=(4, 5), dtype=int32)
Einsum: C = 
 [[208  80 140  28   8]
 [216 176 126   0 154]
 [288  12  56 414 414]
 [272  85  56   0 165]]


If we're only dealing with one matrix (say, when we're calculatating the transpose of matrix A), then -> is not needed.

In [175]:
A = tf.random.uniform([4, 5], 0, 20, dtype = tf.int32)
print("Transpose: AT = ", tf.transpose(A))
print("Einsum: AT = \n", np.einsum("ji", A))

Transpose: AT =  tf.Tensor(
[[10  5 13  9]
 [16  9 13 13]
 [ 9  6  1 17]
 [ 8 16  1  0]
 [ 3 13 10  9]], shape=(5, 4), dtype=int32)
Einsum: AT = 
 [[10  5 13  9]
 [16  9 13 13]
 [ 9  6  1 17]
 [ 8 16  1  0]
 [ 3 13 10  9]]


In [176]:
A = tf.random.uniform([2, 3, 4], 0, 25, dtype = tf.int32)
B = tf.random.uniform([2, 4, 5], 0, 25, dtype = tf.int32)

print("Matmul: C = ", tf.matmul(A, B))
print("Einsum: C = \n", np.einsum("bij, bjk -> bik", A, B))

Matmul: C =  tf.Tensor(
[[[ 997  713  692  678  464]
  [ 357  165  236  225  154]
  [1328  792  773  782  644]]

 [[ 806  906 1073  743 1121]
  [ 338  321  509  524  497]
  [ 349  561  735  599  700]]], shape=(2, 3, 5), dtype=int32)
Einsum: C = 
 [[[ 997  713  692  678  464]
  [ 357  165  236  225  154]
  [1328  792  773  782  644]]

 [[ 806  906 1073  743 1121]
  [ 338  321  509  524  497]
  [ 349  561  735  599  700]]]


A scalar, which has zero dimension, is represented with nothing, a void

In [177]:
A = tf.random.uniform([2, 3, 4], 0, 25, dtype = tf.int32)

print("Sum =", np.sum(A))
print("Einsum =", np.einsum("bij -> ", A))

Sum = 243
Einsum = 243


The axis that we choose to perform calculation on will be deprecated. For instance, if we perform calculation on `axis = 0` then the axis 0 will be deprecated (b)

In [178]:
A = tf.random.uniform([2, 3, 4], 0, 25, dtype = tf.int32)
print(A)

print("\n")

print("Sum 0 =\n", np.sum(A, 0))
print("Einsum 0 =\n", np.einsum("bij -> ij", A))

print("\n")

print("Sum 1 =\n", np.sum(A, 1))
print("Einsum 1 =\n", np.einsum("bij -> bj", A))

print("\n")

print("Sum 2 =\n", np.sum(A, 2))
print("Einsum 2 =\n", np.einsum("bij -> bi", A))

tf.Tensor(
[[[ 8  3 19 20]
  [21  8  2  0]
  [ 4 15 14  9]]

 [[11 18 14  2]
  [20  3 23 17]
  [15  0 16  8]]], shape=(2, 3, 4), dtype=int32)


Sum 0 =
 [[19 21 33 22]
 [41 11 25 17]
 [19 15 30 17]]
Einsum 0 =
 [[19 21 33 22]
 [41 11 25 17]
 [19 15 30 17]]


Sum 1 =
 [[33 26 35 29]
 [46 21 53 27]]
Einsum 1 =
 [[33 26 35 29]
 [46 21 53 27]]


Sum 2 =
 [[50 31 42]
 [45 63 39]]
Einsum 2 =
 [[50 31 42]
 [45 63 39]]


In [179]:
A = tf.random.uniform([2, 3, 4], 0, 25, dtype = tf.int32)
print(A)
print("Shape before:", A.shape)
print("\n")

A_expand = tf.expand_dims(A, axis = 1)
print(A_expand)
print("Shape expand:", A_expand.shape)

A_squeeze = tf.squeeze(A_expand)
print(A_squeeze)
print("Shape squeeze:", A_squeeze.shape)

tf.Tensor(
[[[ 3 20  1  8]
  [13  4 14 21]
  [ 0 23 22  8]]

 [[ 3 17 23  9]
  [ 1  7 12  6]
  [ 9 18 22 18]]], shape=(2, 3, 4), dtype=int32)
Shape before: (2, 3, 4)


tf.Tensor(
[[[[ 3 20  1  8]
   [13  4 14 21]
   [ 0 23 22  8]]]


 [[[ 3 17 23  9]
   [ 1  7 12  6]
   [ 9 18 22 18]]]], shape=(2, 1, 3, 4), dtype=int32)
Shape expand: (2, 1, 3, 4)
tf.Tensor(
[[[ 3 20  1  8]
  [13  4 14 21]
  [ 0 23 22  8]]

 [[ 3 17 23  9]
  [ 1  7 12  6]
  [ 9 18 22 18]]], shape=(2, 3, 4), dtype=int32)
Shape squeeze: (2, 3, 4)


In [180]:
A = tf.random.uniform([1, 4, 1, 3, 1, 5], 0, 25, dtype = tf.int32)
print(tf.squeeze(A).shape)
print(tf.squeeze(A, 0).shape)

(4, 3, 5)
(4, 1, 3, 1, 5)


In [181]:
a = tf.random.uniform([2, 3], 0, 20, dtype = tf.int32)
print(a)

print(tf.reshape(a, [3, 2]))
print(tf.reshape(a, [6]))
print(tf.reshape(a, [2, -1]))
print(tf.reshape(a, [-1]))

tf.Tensor(
[[19 13 19]
 [18 10 18]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[19 13]
 [19 18]
 [10 18]], shape=(3, 2), dtype=int32)
tf.Tensor([19 13 19 18 10 18], shape=(6,), dtype=int32)
tf.Tensor(
[[19 13 19]
 [18 10 18]], shape=(2, 3), dtype=int32)
tf.Tensor([19 13 19 18 10 18], shape=(6,), dtype=int32)


**tf.concat**  
All of the other axes must have the same shape, except for the axis that is being concatenated.

In [182]:
a = tf.random.uniform([2, 4], 0, 10, dtype = tf.int32)
b = tf.random.uniform([3, 4], 10, 20, dtype = tf.int32)
print(a)
print(b)
print(tf.concat([a, b], axis = 0))

c = tf.random.uniform([2, 5], 0, 10, dtype = tf.int32)
d = tf.random.uniform([2, 4], 10, 20, dtype = tf.int32)
print(c)
print(d)
print(tf.concat([c, d], axis = 1))

tf.Tensor(
[[8 1 7 0]
 [5 3 1 1]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[14 15 14 14]
 [10 19 14 18]
 [17 10 12 18]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 8  1  7  0]
 [ 5  3  1  1]
 [14 15 14 14]
 [10 19 14 18]
 [17 10 12 18]], shape=(5, 4), dtype=int32)
tf.Tensor(
[[7 7 0 0 6]
 [0 5 6 3 6]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[12 19 15 19]
 [15 14 14 10]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 7  7  0  0  6 12 19 15 19]
 [ 0  5  6  3  6 15 14 14 10]], shape=(2, 9), dtype=int32)


In [183]:
a = tf.random.uniform([3, 4], 0, 10, dtype = tf.int32)
b = tf.random.uniform([3, 4], 10, 20, dtype = tf.int32)
print(a)
print(b)
print(tf.stack([a, b], axis = 0))

c = tf.random.uniform([3, 5], 0, 10, dtype = tf.int32)
d = tf.random.uniform([3, 5], 10, 20, dtype = tf.int32)
print(c)
print(d)
print(tf.stack([c, d], axis = 2))

tf.Tensor(
[[4 1 6 1]
 [8 5 3 9]
 [6 6 3 2]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[18 10 16 15]
 [10 16 16 11]
 [17 18 16 18]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[ 4  1  6  1]
  [ 8  5  3  9]
  [ 6  6  3  2]]

 [[18 10 16 15]
  [10 16 16 11]
  [17 18 16 18]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[3 5 8 2 0]
 [6 5 6 0 3]
 [3 1 9 7 6]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[15 11 16 19 18]
 [10 18 13 12 16]
 [18 17 18 10 10]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[[ 3 15]
  [ 5 11]
  [ 8 16]
  [ 2 19]
  [ 0 18]]

 [[ 6 10]
  [ 5 18]
  [ 6 13]
  [ 0 12]
  [ 3 16]]

 [[ 3 18]
  [ 1 17]
  [ 9 18]
  [ 7 10]
  [ 6 10]]], shape=(3, 5, 2), dtype=int32)


In [184]:
a = tf.random.uniform([3, 4], 0, 10, dtype = tf.int32)
b = tf.random.uniform([3, 4], 10, 20, dtype = tf.int32)
print(a)
print(b)
print(tf.stack([a, b], axis = 0))
print(tf.concat([tf.expand_dims(t, axis = 0) for t in [a, b]], axis = 0))

tf.Tensor(
[[5 8 0 2]
 [8 4 7 9]
 [7 3 5 8]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[14 15 14 14]
 [11 18 10 11]
 [10 11 13 16]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[[ 5  8  0  2]
  [ 8  4  7  9]
  [ 7  3  5  8]]

 [[14 15 14 14]
  [11 18 10 11]
  [10 11 13 16]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor(
[[[ 5  8  0  2]
  [ 8  4  7  9]
  [ 7  3  5  8]]

 [[14 15 14 14]
  [11 18 10 11]
  [10 11 13 16]]], shape=(2, 3, 4), dtype=int32)


In [185]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 2], [3, 2]])

print(tf.pad(t, paddings, "CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 0 0]
 [0 0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]], shape=(5, 8), dtype=int32)


This operation pads a tensor according to the paddings you specify. `paddings` is an integer tensor with shape `[n, 2]`, where n is the rank of tensor. For each dimension D of input, paddings `[D, 0]` indicates how many values to add before the contents of tensor in that dimension, and paddings `[D, 1]` indicates how many values to add after the contents of tensor in that dimension. If `mode` is "REFLECT" then both paddings`[D, 0]` and paddings `[D, 1]` must be no greater than tensor.`dim_size(D) - 1` (Size/Number of elements of dimension D). If mode is `"SYMMETRIC"` then both paddings `[D, 0]` and paddings`[D, 1]` must be no greater than `tensor.dim_size(D)`.

In [186]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[1, 1], [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "REFLECT"))
print(tf.pad(t, paddings, "SYMMETRIC"))

tf.Tensor(
[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]], shape=(4, 7), dtype=int32)
tf.Tensor(
[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]], shape=(4, 7), dtype=int32)


In [187]:
params = tf.constant([5, 6, 9, 14, 12, 20])
tf_gather_1 = tf.gather(params, [2, 5, 0])
print(tf_gather_1)
tf_gather_2 = tf.gather(params, tf.range(1, 5))
print(tf_gather_2)

tf.Tensor([ 9 20  5], shape=(3,), dtype=int32)
tf.Tensor([ 6  9 14 12], shape=(4,), dtype=int32)


In [188]:
params = tf.random.uniform([4, 5], 0, 20, dtype = tf.int32)
print(params)
a = tf.gather(params, [0, 2], axis = 0)
print(a)
b = tf.gather(params, [0, 2], axis = 1)
print(b)

tf.Tensor(
[[18  8 19 19  6]
 [17  3  3 13  1]
 [ 9  1 13 11  9]
 [ 3 16 18 18 13]], shape=(4, 5), dtype=int32)
tf.Tensor(
[[18  8 19 19  6]
 [ 9  1 13 11  9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[18 19]
 [17  3]
 [ 9 13]
 [ 3 18]], shape=(4, 2), dtype=int32)


In [189]:
params = tf.random.uniform([2, 4, 5], 0, 30, dtype = tf.int32)
print(params)
a = tf.gather(params, [0, 1], axis = 0)
print(a)
b = tf.gather(params, [2, 0], axis = 1)
print(b)

tf.Tensor(
[[[ 2 28 11 14 29]
  [ 1  6 17 18 22]
  [10 23 11 17 22]
  [20 15 20 15 13]]

 [[29 10  0 26 18]
  [15 21  3 29 23]
  [29 29  6  6 15]
  [ 2  9 19 26 18]]], shape=(2, 4, 5), dtype=int32)
tf.Tensor(
[[[ 2 28 11 14 29]
  [ 1  6 17 18 22]
  [10 23 11 17 22]
  [20 15 20 15 13]]

 [[29 10  0 26 18]
  [15 21  3 29 23]
  [29 29  6  6 15]
  [ 2  9 19 26 18]]], shape=(2, 4, 5), dtype=int32)
tf.Tensor(
[[[10 23 11 17 22]
  [ 2 28 11 14 29]]

 [[29 29  6  6 15]
  [29 10  0 26 18]]], shape=(2, 2, 5), dtype=int32)


In [190]:
params = tf.random.uniform([2, 2], 0, 10, dtype = tf.int32)
indices = tf.constant([[1, 0], [0, 1]])
print(params)
a = tf.gather_nd(params, indices)
print(a)

tf.Tensor(
[[1 4]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([5 4], shape=(2,), dtype=int32)


In [191]:
params = tf.random.uniform([3, 2, 2], 0, 10, dtype = tf.int32)
indices = tf.constant([[1, 0], [0, 1]])
print(params)
a = tf.gather_nd(params, indices)
print(a)

tf.Tensor(
[[[6 7]
  [0 0]]

 [[6 8]
  [4 3]]

 [[8 7]
  [2 5]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[6 8]
 [0 0]], shape=(2, 2), dtype=int32)


In [192]:
params = tf.random.uniform([3, 2, 2], 0, 10, dtype = tf.int32)
indices = tf.constant([[1, 0, 1], [0, 1, 0]])
print(params)
a = tf.gather_nd(params, indices)
print(a)

tf.Tensor(
[[[5 6]
  [1 4]]

 [[6 2]
  [9 5]]

 [[4 6]
  [2 4]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor([2 1], shape=(2,), dtype=int32)


In [193]:
params = tf.random.uniform([3, 2, 2], 0, 10, dtype = tf.int32)
indices = tf.constant([[[1, 0],
                        [0, 1]],
                       [[0, 0],
                        [1, 1]]])
print(params)
a = tf.gather_nd(params, indices)
print(a)

tf.Tensor(
[[[7 5]
  [4 2]]

 [[3 2]
  [5 3]]

 [[6 7]
  [1 7]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[3 2]
  [4 2]]

 [[7 5]
  [5 3]]], shape=(2, 2, 2), dtype=int32)


When specifying `batch_dims = 1`, we're essentially saying that the indices match with the params

In [194]:
params = tf.random.uniform([2, 2, 2], 0, 10, dtype = tf.int32)
indices = tf.constant([[1, 0], [0, 1]])
print(params)
a = tf.gather_nd(params, indices, batch_dims = 1)
print(a)

tf.Tensor(
[[[7 0]
  [2 2]]

 [[5 4]
  [4 9]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)


In [195]:
params = tf.random.uniform([3, 2, 2], 0, 10, dtype = tf.int32)
indices = tf.constant([[1, 0],
                       [0, 1],
                       [1, 1]])
print(params)
a = tf.gather_nd(params, indices, batch_dims = 1)
print(a)

tf.Tensor(
[[[1 6]
  [2 8]]

 [[9 3]
  [2 7]]

 [[3 0]
  [9 9]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor([2 3 9], shape=(3,), dtype=int32)


**Ragged Tensor**

In [197]:
tensor_ragged = tf.ragged.constant([[5, 2],
                                    [9, 12, 5],
                                    [18, 11, 25, 10],
                                    [5, 3, 4, 6, 7]])
print(tensor_ragged)
print(tensor_ragged.shape)

<tf.RaggedTensor [[5, 2], [9, 12, 5], [18, 11, 25, 10], [5, 3, 4, 6, 7]]>
(4, None)


`tf.ragged.boolean_mask` to choose which element to show, and which not to

In [199]:
T, F = (True, False)
data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mask=[[T, F, T], [F, F, F], [T, F, F]]
masked_data = tf.ragged.boolean_mask(data, mask)
print(masked_data)

<tf.RaggedTensor [[1, 3], [], [7]]>


We can also choose only the rows, instead of having to manually choose every element

In [201]:
T, F = (True, False)
data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mask=[T, F, T]
masked_data = tf.ragged.boolean_mask(data, mask)
print(masked_data)

tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [206]:
values = [3, 1, 4, 1, 5, 9, 2, 6]
lengths = [4, 0, 3, 1, 0]
row_length_tensor = tf.RaggedTensor.from_row_lengths(values, lengths)
print(row_length_tensor)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


`tf.RaggedTensor.from_row_limits` takes a list of the the elements from the previous index to the current index

In [210]:
values = [3, 1, 4, 1, 5, 9, 2, 6]
limits = [4, 4, 5, 7, 8, 8]
row_limit_tensor = tf.RaggedTensor.from_row_limits(values, limits)
print(row_limit_tensor)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5], [9, 2], [6], []]>


The first element of the split list/array/tensor of `tf.RaggedTensor.from_row_splits()` has to be 0

In [214]:
values = [3, 1, 4, 1, 5, 9, 2, 6]
splits = [0, 4, 4, 5, 7, 8, 8]
row_split_tensor = tf.RaggedTensor.from_row_splits(values, splits)
print(row_split_tensor)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5], [9, 2], [6], []]>


The `lengths` parameter in `tf.RaggedTensor.from_tensor()` specifies how many elements of each row to take

In [215]:
data = tf.random.uniform([3, 3], 0, 12, dtype = tf.int32)
a = tf.RaggedTensor.from_tensor(data, lengths = [2, 3, 0])
print(data)
print(a)

tf.Tensor(
[[5 1 2]
 [3 2 5]
 [1 5 3]], shape=(3, 3), dtype=int32)
<tf.RaggedTensor [[5, 1], [3, 2, 5], []]>


In [221]:
sparse_tensor = tf.sparse.SparseTensor(
    indices = [[1, 3], [5, 6]],
    values = [12, 5],
    dense_shape = [7, 8]
)
print(sparse_tensor)
a = tf.sparse.to_dense(sparse_tensor)
print(a)

SparseTensor(indices=tf.Tensor(
[[1 3]
 [5 6]], shape=(2, 2), dtype=int64), values=tf.Tensor([12  5], shape=(2,), dtype=int32), dense_shape=tf.Tensor([7 8], shape=(2,), dtype=int64))
tf.Tensor(
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0  0  0]], shape=(7, 8), dtype=int32)


In [225]:
string_tensor = tf.constant(["Hello", "I am learning"])
print(tf.strings.join(string_tensor, separator = " "))
print(tf.strings.length(string_tensor))

tf.Tensor(b'Hello I am learning', shape=(), dtype=string)
tf.Tensor([ 5 13], shape=(2,), dtype=int32)


In [226]:
x_var = tf.Variable(tf.constant([12, 5]))
print(x_var)
x_var.assign([5, 12])
print(x_var)
x_var.assign_add([18, 11])
print(x_var)
x_var.assign_sub([11, 18])
print(x_var)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  5], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 5, 12], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([23, 23], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  5], dtype=int32)>
